language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1

install:
   # This is a dependency of our Django test script
 - pip install argparse --use-mirrors

 - pip install -q Django==$DJANGO_VERSION --use-mirrors

 - pip install coverage

 - pip install flake8 --use-mirrors

 - python setup.py develop

before_script:
   # - flake8 --ignore=E501 mbtilesmap

script:
 - coverage run quicktest.py mbtilesmap

after_success:
 - pip install coveralls
 - coveralls
